version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: openrtb-backend
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/app/data/analytics.db
      - JWT_SECRET=your-production-jwt-secret-key
      - JWT_EXPIRY=15m
      - REFRESH_TOKEN_EXPIRY=168h
      - PORT=8080
      - CORS_ORIGINS=http://localhost:3000,http://localhost
      - LOG_LEVEL=info
      - RATE_LIMIT=100
    volumes:
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - openrtb_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: openrtb-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - openrtb_network

volumes:
  backend_data:
    driver: local

networks:
  openrtb_network:
    driver: bridge